# Generated by Django 3.1.6 on 2021-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210212_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
    ]
