# Generated by Django 3.1.6 on 2021-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210213_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='cboice_one',
            new_name='choice_one',
        ),
    ]
